# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at Malik Zeeshan 1122

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [51]:
import numpy as np

#### 1. Import the numpy package under the name `np` (★☆☆)

In [52]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [53]:
np.__version__
np.show_config()

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30152",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.3",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30152",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= 

C:\Users\hp.DESKTOP-G2KULAS\AppData\Roaming\Python\Python312\site-packages\numpy\__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [54]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [55]:
z.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [56]:

z.itemsize

z.nbytes


80

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [57]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [58]:
b = np.zeros(10)
b[5:] = 1
b

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [59]:
c = np.zeros(20)
c[::2] = 1
c

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0.])

In [60]:
d = np.zeros(20)
d[::5] = 100
d

array([100.,   0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0., 100.,
         0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.])

In [61]:
e = np.zeros(20)
e[:1] = 100
e

array([100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [62]:
e1 = np.zeros(20)
e1[1:] = 100
e1

array([  0., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [63]:
f = np.zeros(20)
f[1::5] = 100
f

array([  0., 100.,   0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,
       100.,   0.,   0.,   0.,   0., 100.,   0.,   0.,   0.])

#### 7. Create a vector with values aranging from 10 to 49 (★☆☆)

In [64]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [65]:
b = np.arange(10,51)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [66]:
c = np.arange(10,51,2)
c

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [67]:
d = np.arange(0,25).reshape(5,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
e = np.arange(100,200)
e

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [69]:
f = np.arange(100,200).reshape(10,10)
f[4:6,4:6] = 0
f

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143,   0,   0, 146, 147, 148, 149],
       [150, 151, 152, 153,   0,   0, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [70]:
g = np.arange(0,10),np.arange(10,20),np.arange(20,30)
g

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))

In [71]:
h = np.arange(10,30)
h[::-2] = 0
h

array([10,  0, 12,  0, 14,  0, 16,  0, 18,  0, 20,  0, 22,  0, 24,  0, 26,
        0, 28,  0])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [72]:
# reverse a vector (first element becomes last)
i = np.arange(10,30)
i[::-3] = 100
i 

array([ 10, 100,  12,  13, 100,  15,  16, 100,  18,  19, 100,  21,  22,
       100,  24,  25, 100,  27,  28, 100])

In [73]:
j = np.arange(0,10)
j[2 : -1] = 100
j

array([  0,   1, 100, 100, 100, 100, 100, 100, 100,   9])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [74]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
arr3 = np.arange(12).reshape(3,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
arr4 = np.arange(15).reshape(3,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [77]:
# find indices of non-zero elements from [1,2,0,0,4,0]
arr5 = np.array([1,2,0,0,4,0])
arr5

array([1, 2, 0, 0, 4, 0])

In [78]:
arr6 = np.array([1,2,0,0,4,0])
arr6.nonzero()

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [79]:
arr7 = np.identity(3)
arr7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
arr8 = np.eye(3)
arr8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
arr9 = np.eye(9)
arr9

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [82]:
arr10 = np.random.rand(3,3,3)
arr10

array([[[0.11067007, 0.32571788, 0.82554263],
        [0.11181989, 0.37521186, 0.01566726],
        [0.59171245, 0.72633414, 0.35254086]],

       [[0.02378698, 0.81584878, 0.76973863],
        [0.95930092, 0.40406051, 0.85545807],
        [0.64767532, 0.35990192, 0.32222173]],

       [[0.6585694 , 0.2605172 , 0.27492983],
        [0.95223294, 0.13705256, 0.10384464],
        [0.3488742 , 0.10598361, 0.12939024]]])

In [83]:
arr11 = np.random.rand(10,10)
arr11

array([[0.24802865, 0.41729468, 0.70323749, 0.296034  , 0.25588337,
        0.71524529, 0.19970411, 0.15912405, 0.62344145, 0.40568021],
       [0.92804801, 0.51091183, 0.63130285, 0.28953129, 0.56990336,
        0.0349223 , 0.35884357, 0.86479545, 0.21990584, 0.49961053],
       [0.13116962, 0.46079038, 0.5665373 , 0.65368044, 0.08365316,
        0.53360506, 0.53047019, 0.77431047, 0.1933834 , 0.57105853],
       [0.59074726, 0.51014057, 0.45059371, 0.14566584, 0.89516287,
        0.12127898, 0.75263899, 0.81030699, 0.30487536, 0.12872783],
       [0.54060757, 0.31018858, 0.5637037 , 0.82542298, 0.61813232,
        0.49817038, 0.02438405, 0.80869076, 0.17437323, 0.57162527],
       [0.65922866, 0.34253691, 0.33025392, 0.20159073, 0.21619532,
        0.30121263, 0.8107574 , 0.97087069, 0.67510689, 0.7389851 ],
       [0.67515857, 0.82769973, 0.15635385, 0.89811939, 0.16516594,
        0.14528904, 0.91954052, 0.41784148, 0.83058258, 0.75528334],
       [0.93814582, 0.45503559, 0.7688114

In [84]:
arr12 = np.random.rand(30)
arr12

array([0.94393857, 0.66169804, 0.29662863, 0.43187891, 0.43445395,
       0.21073782, 0.3924748 , 0.09550672, 0.70393074, 0.55106565,
       0.24093825, 0.13657654, 0.18513323, 0.09747255, 0.19286597,
       0.84022116, 0.50917416, 0.07273462, 0.67495928, 0.89259871,
       0.82773366, 0.67922854, 0.9204814 , 0.79395041, 0.78872213,
       0.22031907, 0.88400949, 0.61476634, 0.64649174, 0.62969341])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [85]:
arr13 = np.random.rand(10,10)
arr13

array([[0.16518338, 0.96863003, 0.82778036, 0.03015785, 0.28367325,
        0.35873202, 0.51117984, 0.74296608, 0.91098221, 0.21443772],
       [0.29266226, 0.00222487, 0.56160302, 0.18273979, 0.44745132,
        0.76648702, 0.33493701, 0.13078969, 0.79355704, 0.41265594],
       [0.65397997, 0.48032244, 0.70255407, 0.60943695, 0.75631563,
        0.49535239, 0.13737659, 0.25399752, 0.07321888, 0.01315742],
       [0.74630041, 0.80311241, 0.4079385 , 0.90297856, 0.29663684,
        0.97119765, 0.37456384, 0.39045276, 0.8711038 , 0.40232489],
       [0.59606669, 0.85149175, 0.77964228, 0.6474559 , 0.71072716,
        0.16461552, 0.52391568, 0.90910754, 0.61425147, 0.87410204],
       [0.06376057, 0.07683429, 0.81689286, 0.87600161, 0.82507058,
        0.7857814 , 0.78202495, 0.63391432, 0.3978677 , 0.87712302],
       [0.73009537, 0.84541403, 0.71773973, 0.96920078, 0.77685404,
        0.24825193, 0.17936718, 0.14366274, 0.1480778 , 0.58919653],
       [0.52048803, 0.70758176, 0.2981131

In [86]:
arr13.min()


0.002224874874544258

In [87]:
arr13.max()

0.9711976479815623

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [88]:
arr14 = np.random.rand(30)
arr13.mean()

0.5133740132197524

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [89]:
# Create a 2d array with 1 on the border and 0 inside
arr15 = np.ones((10,10))
arr15[1:-1,1:-1] = 0
arr15


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [90]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 100
arr

array([[  1.,   1.,   1.,   1.,   1.],
       [  1., 100., 100., 100.,   1.],
       [  1., 100., 100., 100.,   1.],
       [  1., 100., 100., 100.,   1.],
       [  1.,   1.,   1.,   1.,   1.]])

In [91]:
arr2 = np.ones((5,5))
arr2[1:-2,1:-2] = 100
arr2

array([[  1.,   1.,   1.,   1.,   1.],
       [  1., 100., 100.,   1.,   1.],
       [  1., 100., 100.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.]])

In [92]:
arr3 = np.ones((5,5))
arr3[1:-2,1:-2] = 100
arr3

array([[  1.,   1.,   1.,   1.,   1.],
       [  1., 100., 100.,   1.,   1.],
       [  1., 100., 100.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.]])

In [93]:
arr4 = np.ones((5,5))
arr4[1:-3,1:-3] = 100
arr4 

array([[  1.,   1.,   1.,   1.,   1.],
       [  1., 100.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.]])

In [94]:
arr3 = np.ones((5,5))
arr3[2:-2,2:-2] = 100
arr3

array([[  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1., 100.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [95]:
# How to add a border (filled with 0's) around an existing array?
arr = np.ones((5,5))
arr

arr2 = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
arr2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [96]:
arr3 = np.ones((5,5))
arr3[1:-1,1:-1] = 0

arr3

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [97]:

# What is the result of the following expression?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [98]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
arr18 = np.diag(1+np.arange(4),k = -1)
arr18


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [99]:
arr = np.diag(1+np.arange(4), k = -4)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0]])

In [100]:
arr = np.diag(1+np.arange(7), k = -1)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [101]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
arr19 = np.zeros((8,8),dtype=int)
arr19

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [102]:
# Condier a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
arr20 = np.unravel_index(100,(6,7,8))
arr20


(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [103]:
# Create a checkerboard 8x8 matrix using the tile function
arr21 = np.tile(np.array([[0,1],[1,0]]),(4,4))
arr21


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [104]:
arr = np.tile(np.array([[0,1],[1,0]]),(4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [105]:
arr2 = np.tile(np.array([[100,200],[200,100]]),(4,4))
arr2

array([[100, 200, 100, 200, 100, 200, 100, 200],
       [200, 100, 200, 100, 200, 100, 200, 100],
       [100, 200, 100, 200, 100, 200, 100, 200],
       [200, 100, 200, 100, 200, 100, 200, 100],
       [100, 200, 100, 200, 100, 200, 100, 200],
       [200, 100, 200, 100, 200, 100, 200, 100],
       [100, 200, 100, 200, 100, 200, 100, 200],
       [200, 100, 200, 100, 200, 100, 200, 100]])

### 22. Normalize a 5x5 random matrix (★☆☆)

In [106]:
# Normalize a 5x5 random matrix
arr22 = np.random.normal((5,5))
arr22


array([5.90411129, 3.80979233])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [107]:
import numpy as np

# Create a custom dtype for RGBA color
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Example usage
color = np.array([(255, 0, 0, 255)], dtype=color_dtype)
print(color)


[(255, 0, 0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [108]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
arr24 = np.dot(np.ones((5,3)),np.ones((3,2)))
arr24


array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [109]:
arr = np.dot(np.zeros((5,4)),np.zeros((4,4)))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [110]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
arr25 = np.arange(11)
arr25[(3 < arr25) & (arr25 < 8)] *= -1
arr25


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author Muhammad Zeeshan

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [111]:
# What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))




10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [112]:
# Consider an integer vector Z, which of these expressions are legal?

Z = 10

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

False

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [113]:
# What are the result of the following expressions?
np.array(0) / np.array(0)

nan

In [114]:
np.array(0) // np.array(0)

0

In [115]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [116]:
# How to round away from zero a float array ?
Z = np.random.uniform(-10,+10,10)
Z

array([-6.26254062,  7.13095042, -5.30405854, -8.25814534,  1.99005459,
        4.15117653, -7.414215  , -7.43854098,  5.71875945,  2.34616885])

#### 30. How to find common values between two arrays? (★☆☆)

In [117]:
# How to find common values between two arrays?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
Z1

array([5, 2, 5, 0, 8, 4, 4, 7, 5, 7])

In [118]:
Z = np.intersect1d(Z1,Z2)
Z

array([2, 5, 7, 8])

In [119]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
c = np.intersect1d(a,b)
c

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [120]:
# How to ignore all numpy warnings (not recommended)?
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
Z 


array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [121]:
# Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [122]:
# How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
yesterday

numpy.datetime64('2023-11-19')

In [123]:
today = np.datetime64('today','D')
today

numpy.datetime64('2023-11-20')

In [124]:
tomarrow = np.datetime64('today','D') + np.timedelta64(1,'D')
tomarrow

numpy.datetime64('2023-11-21')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [125]:
# How to get all the dates corresponding to the month of July 2016?
Z = np.arange('2016-07','2016-08',dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [126]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
A

array([1., 1., 1.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [127]:
# Extract the integer part of a random array using 5 different methods
Z = np.random.uniform(0,10,10)
Z

Z - Z%1


array([8., 5., 6., 1., 5., 1., 7., 8., 7., 7.])

In [128]:
np.floor(Z)

array([8., 5., 6., 1., 5., 1., 7., 8., 7., 7.])

In [129]:
np.ceil(Z)-1

array([8., 5., 6., 1., 5., 1., 7., 8., 7., 7.])

In [130]:
Z.astype(int)

array([8, 5, 6, 1, 5, 1, 7, 8, 7, 7])

In [131]:
np.trunc(Z)

array([8., 5., 6., 1., 5., 1., 7., 8., 7., 7.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [132]:
# Create a 5x5 matrix with row values ranging from 0 to 4
Z = np.zeros((5,5))
Z = Z + np.arange(5)
Z


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [140]:
# Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x     

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [141]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
Z = np.linspace(0,1,11,endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [142]:
# Create a random vector of size 10 and sort it
Z = np.random.random(10)
Z.sort()
Z

array([0.18503057, 0.2559692 , 0.34048212, 0.34223071, 0.40109629,
       0.49797153, 0.58798038, 0.66964799, 0.69001934, 0.71263589])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [145]:
# How to sum a small array faster than np.sum?
Z = np.arange(10)
np.sum(Z)

np.add.reduce(Z)



45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [146]:
# Consider two random array A and B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
A

array([1, 1, 1, 1, 0])

In [147]:
B 

array([1, 0, 0, 0, 0])

In [148]:
equal = np.allclose(A,B)
equal

False

#### 43. Make an array immutable (read-only) (★★☆)

In [149]:
# Make an array immutable (read-only)
Z = np.zeros(10)
Z.flags.writeable = False
Z


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [150]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
Z = np.random.random((10,2))
Z

array([[0.24000986, 0.60803845],
       [0.3501544 , 0.01904514],
       [0.15838265, 0.35136243],
       [0.36582399, 0.28128727],
       [0.98398709, 0.41894189],
       [0.9746299 , 0.66880827],
       [0.13542244, 0.9140709 ],
       [0.47580916, 0.3607992 ],
       [0.36616139, 0.27583289],
       [0.51686744, 0.5891212 ]])

In [151]:
X,Y = Z[:,0], Z[:,1]
X

array([0.24000986, 0.3501544 , 0.15838265, 0.36582399, 0.98398709,
       0.9746299 , 0.13542244, 0.47580916, 0.36616139, 0.51686744])

In [152]:
Y


array([0.60803845, 0.01904514, 0.35136243, 0.28128727, 0.41894189,
       0.66880827, 0.9140709 , 0.3607992 , 0.27583289, 0.5891212 ])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [153]:
# Create random vector of size 10 and replace the maximum value by 0
Z = np.random.rand(10)
Z

array([0.08477402, 0.90378784, 0.7085946 , 0.9889896 , 0.50717168,
       0.53838722, 0.52458417, 0.17759469, 0.35402594, 0.861008  ])

In [154]:
Z[Z.argmax()] = 0
Z

array([0.08477402, 0.90378784, 0.7085946 , 0.        , 0.50717168,
       0.53838722, 0.52458417, 0.17759469, 0.35402594, 0.861008  ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [155]:
# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
Z = np.zeros((5,5), [('x',float),('y',float)])
Z

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [158]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
X = np.arange(8)
X

Y = X + 0.5
Y


C = 1.0 / np.subtract.outer(X, Y)

np.linalg.det(C)

3638.163637117973

In [157]:
C = 1.0 / np.subtract.outer(X, Y)

np.linalg.det(C)


3638.163637117973

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [159]:
# Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### 49. How to print all the values of an array? (★★☆)

In [163]:
# How to print all the values of an array?


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [165]:
# How to find the closest value (to a given scalar) in a vector?
Z = np.arange(100)
Z

v = np.random.uniform(0,100)
v

index = (np.abs(Z-v)).argmin()

Z[index]


73

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [166]:
# create a structured array representing a position (x,y) and a color (r,g,b)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
                   ('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
                   

C:\Users\hp.DESKTOP-G2KULAS\AppData\Local\Temp\ipykernel_5908\653241344.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [167]:
# Consider a random vector with shape (100,2) representing coordinates, find point by point distances
Z = np.random.random((10,2))
Z

array([[0.48527871, 0.31872922],
       [0.19563013, 0.73504019],
       [0.74036248, 0.20102631],
       [0.06319183, 0.43681029],
       [0.08353941, 0.68497873],
       [0.11585453, 0.98610337],
       [0.73986775, 0.64457736],
       [0.42918264, 0.92239815],
       [0.49929982, 0.03574325],
       [0.39805103, 0.7182182 ]])

In [168]:
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
X


array([[0.48527871, 0.19563013, 0.74036248, 0.06319183, 0.08353941,
        0.11585453, 0.73986775, 0.42918264, 0.49929982, 0.39805103]])

In [169]:
Y 

array([[0.31872922, 0.73504019, 0.20102631, 0.43681029, 0.68497873,
        0.98610337, 0.64457736, 0.92239815, 0.03574325, 0.7182182 ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [171]:
# How to convert a float (32 bits) array into an integer (32 bits) in place?
Z =  np.arange(10, dtype = np.float32)
Z


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [174]:

# How to read the following file?
from io import StringIO

# Fake file

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
Z

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [175]:

# What is the equivalent of enumerate for numpy arrays?

Z = np.arange(9).reshape(3,3)
Z

for index, value in np.ndenumerate(Z):
    print(index, value)

for index in np.ndindex(Z.shape):
    print(index, Z[index])
    

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [176]:
# Generate a generic 2D Gaussian-like array
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)    
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
G


array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [177]:
# How to randomly place p elements in a 2D array?

n = 10
p = 3
Z = np.zeros((n,n))

np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
Z


array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [178]:
# Subtract the mean of each row of a matrix
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)
Y


array([[-0.39581411, -0.04588237,  0.08845488, -0.00804648,  0.05567725,
        -0.12948267,  0.33168365, -0.38613727,  0.04218537,  0.44736174],
       [-0.4893348 , -0.20057677,  0.39272069,  0.31420422,  0.05516784,
         0.17321164, -0.09221613,  0.28223087, -0.5206502 ,  0.08524264],
       [-0.32028687,  0.35677694, -0.08787111,  0.05491776, -0.30820769,
         0.33149763, -0.15000817,  0.4913806 , -0.27157077, -0.09662833],
       [ 0.24444956, -0.02985902,  0.17394767,  0.2247298 , -0.10504094,
         0.26777306, -0.33877574,  0.02310899, -0.34921227, -0.11112111],
       [-0.52082128,  0.30312443, -0.2264167 , -0.0784515 ,  0.2542944 ,
        -0.21490631,  0.31855235, -0.09049678,  0.41475654, -0.15963516]])

#### 59. How to sort an array by the nth column? (★★☆)

In [179]:
# How to sort an array by the nth column?
Z = np.random.randint(0,10,(3,3))
Z


array([[7, 3, 6],
       [1, 9, 4],
       [1, 6, 8]])

In [180]:
Z[Z[:,1].argsort()]

array([[7, 3, 6],
       [1, 6, 8],
       [1, 9, 4]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [191]:
# How to tell if a given 2D array has null columns
z = np.full((10,10), 0)
z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [193]:
# Find the nearest value from a given value in an array
Z = np.random.uniform(0,1,10)
Z


array([0.63159283, 0.59701896, 0.41919236, 0.27561717, 0.71191418,
       0.54142265, 0.52907954, 0.51962555, 0.00190166, 0.57715378])

In [194]:

z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
m

0.519625545453541

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [200]:
# considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?    

A = np.arange(3).reshape(3,1)

B = np.arange(3).reshape(1,3)

it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y

it.operands[2]







array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 63. Create an array class that has a name attribute (★★☆)

In [204]:
# Create an array class that has a name attribute

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):

        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
Z.name


'range_10'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [206]:
# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
I

Z += np.bincount(I, minlength=len(Z))

Z

np.add.at(Z, I, 1)

Z





array([ 5.,  7.,  7.,  1.,  5.,  5.,  1.,  1.,  5., 13.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [207]:
# How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
X = [1,2,3,4,5,6]

I = [1,3,9,3,4,1]

F = np.bincount(I,X)
F


array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [208]:
# Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
I


array([[[0, 1, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 0, 0],
        [1, 1, 1],
        [1, 0, 0],
        [0, 1, 1],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [1, 1, 1],
        [0, 1, 0],
        [1, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
        [0, 1, 1]],

       [[1, 0, 0],
        [0, 1, 1],
        [0, 0, 1],
        [0, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [1, 1, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 1, 1],
        [1, 0, 0],
        [0, 0, 1]],

       [[1, 1, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 1, 0],
        [0, 0, 0],
        [1, 0, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [0, 0, 1],
        [1, 0, 1],
        [0, 0, 0],
        [1, 0, 0],
        [1, 1, 0],
        [0, 1, 1]],

       [[1, 1, 1],
        [1, 0, 0],
        [0, 1, 1],
        [0, 0, 1],
      

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [212]:
# Considering a four dimensions array, how to get sum over the last two axis at once?
A = np.random.randint(0,10,(3,4,3,4))
A 

array([[[[3, 1, 4, 0],
         [2, 7, 5, 5],
         [2, 5, 1, 3]],

        [[6, 2, 8, 8],
         [6, 2, 7, 5],
         [5, 7, 1, 1]],

        [[1, 3, 1, 8],
         [7, 3, 8, 9],
         [1, 8, 3, 4]],

        [[9, 4, 9, 8],
         [7, 2, 8, 1],
         [3, 5, 2, 8]]],


       [[[6, 4, 4, 2],
         [0, 3, 5, 0],
         [5, 6, 7, 4]],

        [[2, 9, 4, 9],
         [1, 7, 9, 3],
         [5, 6, 2, 8]],

        [[9, 6, 5, 2],
         [3, 2, 5, 9],
         [3, 0, 0, 1]],

        [[1, 5, 7, 4],
         [9, 9, 0, 0],
         [3, 1, 0, 6]]],


       [[[4, 7, 1, 4],
         [0, 9, 6, 6],
         [2, 8, 1, 5]],

        [[8, 0, 7, 7],
         [4, 1, 6, 7],
         [2, 1, 0, 5]],

        [[1, 2, 4, 8],
         [2, 6, 7, 8],
         [1, 2, 8, 9]],

        [[6, 1, 7, 6],
         [9, 2, 6, 2],
         [3, 1, 0, 7]]]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [213]:
# Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
D = np.random.uniform(0,1,100)
D


array([0.6112494 , 0.60860843, 0.37221622, 0.70641218, 0.75803022,
       0.16874808, 0.0108732 , 0.72124748, 0.15817328, 0.56749966,
       0.93709236, 0.41088179, 0.30143842, 0.58582229, 0.90885207,
       0.64038215, 0.92002148, 0.56051397, 0.23446776, 0.61005542,
       0.8106754 , 0.1588952 , 0.60275936, 0.69842193, 0.45117921,
       0.24379876, 0.39287638, 0.56727839, 0.3171351 , 0.80023359,
       0.28208962, 0.82672966, 0.50662213, 0.53502906, 0.11884579,
       0.2255399 , 0.74106338, 0.37281852, 0.35531375, 0.82289496,
       0.2167555 , 0.93056986, 0.20240629, 0.3878255 , 0.25528577,
       0.98409181, 0.18958505, 0.69181176, 0.24699189, 0.37469621,
       0.37063491, 0.4200605 , 0.0750764 , 0.1964067 , 0.60029018,
       0.70408596, 0.50553687, 0.97634314, 0.52613633, 0.40115219,
       0.47945373, 0.69394398, 0.24414278, 0.35884126, 0.25783494,
       0.38895471, 0.34927681, 0.75698881, 0.30099954, 0.27647024,
       0.15139553, 0.24045221, 0.23195634, 0.36449261, 0.66805

#### 69. How to get the diagonal of a dot product? (★★★)

In [224]:
# How to get the diagonal of a dot product?
A = np.random.uniform(0,1,(5,5))
A

B = np.random.uniform(0,1,(5,5))
B

np.sum(A * B.T, axis=1)

np.diag(np.dot(A, B))


array([1.29280333, 1.90569823, 1.91841018, 0.96915115, 0.88737357])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [226]:
# Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

Z = np.array([1,2,3,4,5])
Z

nz = 3

Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0

Z0[::nz+1] = Z
Z0




array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [227]:
# Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
A = np.ones((5,5,3))

B = 2*np.ones((5,5))

A * B[:,:,None]


array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [262]:
# How to swap two rows of an array?
A = np.arange(25).reshape(5,5)
A

A[[1,0]] = A[[4,0]]
A


array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [267]:
# Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles
faces = np.random.randint(0,100,(10,3))
faces

F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F

F = F.reshape(len(F)*3,2)

F



array([[97, 19],
       [19, 93],
       [93, 97],
       [13, 30],
       [30, 86],
       [86, 13],
       [26, 88],
       [88, 31],
       [31, 26],
       [13, 21],
       [21, 39],
       [39, 13],
       [27, 96],
       [96, 68],
       [68, 27],
       [75, 25],
       [25, 67],
       [67, 75],
       [ 0, 23],
       [23, 65],
       [65,  0],
       [53, 95],
       [95,  6],
       [ 6, 53],
       [77, 70],
       [70, 49],
       [49, 77],
       [49, 33],
       [33, 63],
       [63, 49]])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [269]:
# Given an sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?
C = np.bincount([1,1,2,3,4,4,6])
C

A = np.repeat(np.arange(len(C)), C)
A




array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [272]:
# How to compute averages using a sliding window over an array?

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n



    

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
# Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is
# shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
Z = np.arange(10)
Z

from numpy.lib import stride_tricks

R = stride_tricks.as_strided(Z,(8,3),(4,4))


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [274]:
# How to negate a boolean, or to change the sign of a float inplace?

Z = np.random.randint(0,2,100)
Z

np.logical_not(Z, out=Z)


array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [276]:
# Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))


P0 = np.random.uniform(-10,10,(10,2))
P0

P1 = np.random.uniform(-10,10,(10,2))
P1

p  = np.random.uniform(-10,10,( 1,2))
p

distance(P0, P1, p)





array([17.87340382, 10.52699721, 11.8500162 ,  2.53748534,  2.59136182,
        8.90164573,  8.30713049,  2.47961727, 11.26902625,  4.19198542])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [278]:
# Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

def distance(P0, P1, p):

    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))


P0 = np.random.uniform(-10,10,(10,2))
P0

array([[ 6.433465  , -8.9629045 ],
       [ 4.54584015, -0.76559555],
       [-1.33512541, -5.06490952],
       [ 0.29136183,  3.90741806],
       [-8.09668669, -4.26794016],
       [-4.35094823,  4.04045228],
       [ 2.70555725, -5.79419206],
       [ 4.7289588 ,  0.46263098],
       [-2.63685173,  8.01911675],
       [ 9.72043133, -6.39554375]])

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [280]:
# Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)
Z = np.random.randint(0,10,(10,10))
Z

shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
R



array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [286]:
# Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,
# [11,12,13,14]]?
Z = np.arange(1,15,dtype=np.uint32)
Z



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=uint32)

#### 82. Compute a matrix rank (★★★)

In [287]:
# Compute a matrix rank
Z = np.random.uniform(0,1,(10,10))
Z


array([[0.63044074, 0.07455226, 0.73545876, 0.61612747, 0.8314273 ,
        0.92362137, 0.26654146, 0.06937374, 0.82626384, 0.07500169],
       [0.6939377 , 0.0363844 , 0.52449077, 0.55335069, 0.20843466,
        0.68603455, 0.97336092, 0.31126801, 0.64291906, 0.9314729 ],
       [0.74009731, 0.99421495, 0.74122132, 0.00791518, 0.97321948,
        0.94920414, 0.9935899 , 0.50354049, 0.30147848, 0.53408572],
       [0.63540557, 0.04926772, 0.52908809, 0.94189778, 0.45844201,
        0.72441285, 0.27994063, 0.73368812, 0.77361517, 0.69822745],
       [0.33812149, 0.57609695, 0.01975091, 0.05940775, 0.26393012,
        0.07165967, 0.37032443, 0.59802392, 0.11939569, 0.73971298],
       [0.97996421, 0.07372942, 0.46693011, 0.35350717, 0.38455432,
        0.64090459, 0.92616192, 0.32954666, 0.21754323, 0.19587203],
       [0.4647296 , 0.51770149, 0.21356839, 0.96198966, 0.77271452,
        0.75488594, 0.77360512, 0.99408018, 0.72869022, 0.88079052],
       [0.14146887, 0.23989765, 0.7570788

#### 83. How to find the most frequent value in an array?

In [290]:
# How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
Z

np.bincount(Z).argmax()



1

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [294]:
# Extract all the contiguous 3x3 blocks from a random 10x10 matrix
Z = np.random.randint(0,5,(10,10))
Z



array([[0, 2, 3, 4, 0, 3, 1, 1, 2, 4],
       [3, 0, 3, 4, 3, 0, 4, 3, 2, 1],
       [4, 0, 0, 1, 4, 3, 0, 3, 0, 3],
       [3, 4, 0, 1, 0, 2, 1, 3, 1, 0],
       [1, 1, 2, 1, 0, 0, 0, 1, 1, 3],
       [3, 4, 4, 3, 0, 0, 3, 4, 2, 4],
       [0, 0, 2, 2, 1, 1, 4, 2, 2, 4],
       [3, 0, 1, 2, 2, 2, 3, 0, 3, 2],
       [4, 0, 2, 3, 2, 4, 4, 2, 1, 1],
       [2, 2, 3, 4, 1, 0, 2, 1, 3, 3]])

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [295]:
# Create a 2D array subclass such that Z[i,j] == Z[j,i]

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S

Symetric([[ 2,  9,  3,  9, 10],
          [ 9,  5,  6, 12, 10],
          [ 3,  6,  3,  9,  3],
          [ 9, 12,  9,  6,  7],
          [10, 10,  3,  7,  8]])

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [299]:
# Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once?
p, n = 10, 20
M = np.ones((p,n,n))
M


array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       ...,

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1.

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [305]:
# Consider a 16x16 array, how to get the block-sum (block size is 4x4 Z = np.ones(0,4,(16,16))
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S                                       


array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [308]:
# How to implement the Game of Life using numpy arrays?

def iterate(Z):

    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +Z[1:-1,0:-2] + Z[1:-1,2:] + Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)

    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z


Z = np.random.randint(0,2,(50,50))
Z







array([[0, 0, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 1, 1, ..., 1, 0, 1],
       ...,
       [0, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 0, 0]])

#### 89. How to get the n largest values of an array (★★★)

In [311]:
# How to get the n largest values of an array
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

# Create a record array from a regular array?

Z = np.array([("Hello", 2.5, 3),
                ("World", 3.6, 2)])
Z


[9995 9996 9997 9998 9999]
[9997 9999 9998 9996 9995]


array([['Hello', '2.5', '3'],
       ['World', '3.6', '2']], dtype='<U32')

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [317]:
# Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)
    
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    
    return ix
    
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))



[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [318]:
# How to create a record array from a regular array?

Z = np.array([("Hello", 2.5, 3),
                ("World", 3.6, 2)])
Z


array([['Hello', '2.5', '3'],
       ['World', '3.6', '2']], dtype='<U32')

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [320]:
# Consider a large vector Z, compute Z to the power of 3 using 3 different methods









TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [322]:
# Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
A

B = np.random.randint(0,5,(2,2))
B

C = (A[..., np.newaxis, np.newaxis] == B)
C


array([[[[False,  True],
         [False,  True]],

        [[False, False],
         [ True, False]],

        [[False, False],
         [ True, False]]],


       [[[False,  True],
         [False,  True]],

        [[False, False],
         [False, False]],

        [[False,  True],
         [False,  True]]],


       [[[False, False],
         [False, False]],

        [[False, False],
         [False, False]],

        [[False, False],
         [False, False]]],


       [[[False, False],
         [False, False]],

        [[False, False],
         [False, False]],

        [[False, False],
         [ True, False]]],


       [[[False,  True],
         [False,  True]],

        [[False, False],
         [False, False]],

        [[False, False],
         [ True, False]]],


       [[[False, False],
         [False, False]],

        [[False, False],
         [ True, False]],

        [[False, False],
         [False, False]]],


       [[[False, False],
         [False, False]],



#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [324]:
# Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

Z = np.random.randint(0,5,(10,3))
Z

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
E

U = Z[~E]
U

array([[3, 0, 2],
       [4, 3, 0],
       [2, 0, 2],
       [2, 4, 0],
       [0, 4, 2],
       [3, 2, 1],
       [4, 0, 3],
       [0, 2, 1],
       [0, 4, 2],
       [1, 3, 0]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [326]:
# Convert a vector of ints into a matrix binary representation

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
I

B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
B[:,::-1]



array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [328]:
# Given a two dimensional array, how to extract unique rows?

Z = np.unique(np.random.randint(0,2,(6,3)), axis=0)
Z

array([[0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [329]:
# Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

A = np.random.uniform(0,1,10)
A

B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)

np.einsum('i,i->i', A, B)    # A * B

np.einsum('i,i', A, B)    # np.inner(A, B)

np.einsum('i,j->ij', A, B)    # np.outer(A, B)



array([[7.04801906e-02, 2.58288189e-01, 1.08936979e-02, 9.31252785e-02,
        3.05684153e-02, 2.58128347e-01, 4.57889313e-01, 2.49480641e-01,
        3.78332165e-01, 1.71397918e-01],
       [1.21999156e-01, 4.47089329e-01, 1.88566736e-02, 1.61197143e-01,
        5.29130361e-02, 4.46812647e-01, 7.92593058e-01, 4.31843720e-01,
        6.54881953e-01, 2.96684802e-01],
       [8.48280727e-03, 3.10868758e-02, 1.31113635e-03, 1.12083095e-02,
        3.67913272e-03, 3.10676376e-02, 5.51103333e-02, 3.00268228e-02,
        4.55350477e-02, 2.06289951e-02],
       [2.68638461e-03, 9.84477214e-03, 4.15218263e-04, 3.54951246e-03,
        1.16512909e-03, 9.83867968e-03, 1.74526600e-02, 9.50906842e-03,
        1.44203030e-02, 6.53290983e-03],
       [4.11003939e-02, 1.50620284e-01, 6.35263995e-03, 5.43058354e-02,
        1.78259153e-02, 1.50527073e-01, 2.67017313e-01, 1.45484179e-01,
        2.20623709e-01, 9.99503819e-02],
       [1.28810796e-01, 4.72051890e-01, 1.99095076e-02, 1.70197344e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [331]:
# Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

phi = np.arange(0, 10*np.pi, 0.1)
phi



array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9,
       11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [332]:
# Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])

n = 4

M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)

M &= (X.sum(axis=-1) == n)

X[M]



array([[2., 0., 1., 1.]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [333]:
# Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

X = np.random.randn(100) # random 1D array
X

N = 1000 # number of bootstrap samples

idx = np.random.randint(0, X.size, (N, X.size))

means = X[idx].mean(axis=1)

np.percentile(means, [2.5, 97.5])



array([0.03099802, 0.42555029])

In [ ]:
# condider a linear regresion model z = w.x + b where x is input and z is output, 





